### ISSUE TITLE
Footer "credit" links are broken.

### ISSUE THREAD

**Issue by Sntax** [Sntax/LaunchingBalloons#12]
In the footer, the "Cole Gentry" and "Andrew Hill" credit links are currently broken.

**Comment by Sntax** [comment]
@SomethingNew71 - Open to suggestions as to where these should point. Perhaps our GitHub profiles for now?

**Comment by SomethingNew71** [comment]
Yeah I am gonna point them to our github pages.  That was the plan  and I just forgot to populate those links.
